#include "Airplane.h"
#include <ctime>

std::string name_and_surname_arr[300] = {
"Roxie Byrne",
"Jenson Haigh",
"Nida Lam",
"Scarlett-Rose Hendricks",
"Ruby Calderon",
"Tobias Li",
"Eadie Irving",
"Pascal Wills",
"Rian Davila",
"Jordana Bateman",
"Ernie Denton",
"Areebah Kent",
"Nate Pierce",
"Alec Sears",
"Miller Humphries",
"Tiana Marriott",
"Sarah Tang",
"Marley Hunter",
"Yaseen Cantu",
"Aleksandra Bloom",
"Anabella Gunn",
"Mattie Draper",
"Penelope Robertson",
"Jermaine Whitley",
"Denis Duffy",
"Saqib Rubio",
"Callum Day",
"Jillian Power",
"Alistair Cottrell",
"Courtney Rowland",
"Elena Yoder",
"Teddie Cummings",
"Leanne Cisneros",
"Rickie Hubbard",
"Krzysztof Foreman",
"Poppy Devlin",
"Avani Rush",
"Paris Maddox",
"Marcie Koch",
"Taybah Briggs",
"Preston Keller",
"Leonie Barry",
"Mia Doherty",
"Huw Mendoza",
"Mohamad Shields",
"Humaira Dotson",
"Avaya Sullivan",
"Simeon Chase",
"Alana Vang",
"Meera Magana",
"Jordan Newman",
"Nour Byers",
"Madelyn Emery",
"Bartlomiej Preston",
"Harriette Levy",
"Jad East",
"Deen Cohen",
"Isabell Price",
"Jokubas Novak",
"Mairead Green",
"Rahima Short",
"Harlan Olsen",
"Chelsea Mccartney",
"Freddie Woodcock",
"Leopold Finnegan",
"Karter Alexander",
"Sohaib Sadler",
"Shiv Montgomery",
"Beatriz Delaney",
"Alannah Harper",
"Reagan Lawrence",
"Nishat Roberson",
"Bilal Kelley",
"Taine Mellor",
"Rafael Ho",
"Viktor Paul",
"Maheen Greer",
"Eva Delacruz",
"Leonidas Haworth",
"Grayson Hough",
"Norma Lugo",
"Khadeeja Aguirre",
"Neriah Shepherd",
"Grady Bowden",
"Megan Kline",
"Poppie Deacon",
"Kirk Beech",
"John-Paul Washington",
"Yosef Gilliam",
"Naeem Phan",
"Andrea Stout",
"Charles Mcleod",
"Atlanta Mills",
"Duane Fuller",
"Ariyah Shea",
"Una Shannon",
"Betsy Bannister",
"Katerina Cole",
"Lavinia Sharp",
"Beyonce Monte",
"Corinne Mcmanus",
"Montgomery Prosser",
"Denny Field",
"Taryn Rosas",
"Ellie Tang",
"Ronnie Cook",
"Kirsten Whyte",
"Ibraheem Appleton",
"Fatima Mckenna",
"Sakina Lutz",
"Izaan Wynn",
"Khloe Melton",
"Akash Holden",
"Cecil Harper",
"Neive Moses",
"Alessandra Mcgrath",
"Ammara Erickson",
"Anjali Pacheco",
"Franco Graham",
"Shazia Sears",
"Melina Chambers",
"Keeva Lucero",
"Malcolm Sheppard",
"Lindsay Higgins",
"Maisha Harding",
"Dominykas Montoya",
"Catrina Crawford",
"Heena Bravo",
"Ioana Mullen",
"Jordon Mitchell",
"Harmony Healy",
"Izabelle Sanders",
"Lewie Delaney",
"Giacomo Delacruz",
"Sam Rivas",
"Polly Hodson",
"Gregg David",
"Simon Mueller",
"Lyra Albert",
"Daanyal Holman",
"Elise Watt",
"Fredrick Vu",
"Kirandeep Miranda",
"Veronica Schroeder",
"Ira Carpenter",
"Denise Daugherty",
"Ptolemy Rojas",
"Tommy Hendricks",
"Kacie Vega",
"Findlay Trevino",
"Elliott Gunn",
"Shaunna Graves",
"Arjun Hutchings",
"Precious Villanueva",
"Ella-Mae Berg",
"Mildred Stubbs",
"Ashwin Thomson",
"Taio Sweeney",
"Aras Harrington",
"Jace Ramsey",
"Skye Allen",
"Lia Greenaway",
"Digby Mcfadden",
"Willard Hawkins",
"Kristi Matthews",
"Gwion Salinas",
"Hadiya Coles",
"Sulaiman Conrad",
"Zayan Weston",
"Eshan Curry",
"Liam Salazar",
"Mallory Watts",
"Coco Robbins",
"Payton Daniel",
"Ruth Beach",
"Zakariyah Ali",
"Zaynab Petersen",
"Kathleen Howarth",
"Stacie Lawrence",
"Rocco Waters",
"Tayyab Brewer",
"Carrie Byrne",
"Abi Buckley",
"Daisy-Mae Villa",
"Jareth Price",
"Nafisa Foley",
"Chris Bartlett",
"Rehaan O'Neill",
"Amie Huff",
"Philippa Ferreira",
"Dafydd Foster",
"Muna Duffy",
"Gary Goff",
"Spencer Booth",
"Israr Mackay",
"Katya Tierney",
"Aurelia Kramer",
"Alfie-Jay Castaneda",
"Kai Strong",
"Ayla Farmer",
"Amin Lowry",
"Fatimah Bob",
"Vivien Kearns",
"Keeleigh Pike",
"Shakir Hines",
"Khia Hahn",
"Pawel Hulme",
"Olivia-Grace Turnbull",
"Martyn Horne",
"Subhaan Mcmillan",
"India Phillips",
"Haleemah Klein",
"Rikesh Mccarty",
"Ilayda Donnelly",
"Jai Drake",
"Tommy-Lee Dyer",
"Shazia Meadows",
"Aman Huff",
"Alara Prentice",
"Sheikh Meza",
"Roshni Wilkerson",
"Blaine Guerrero",
"Keisha Matthams",
"Jeanne Dickson",
"Darius Joyce",
"Bear Schultz",
"Clinton Reese",
"Dottie Legge",
"Jem Bullock",
"Stephanie Riddle",
"Kendra Valencia",
"Kurt Aldred",
"Arielle Schneider",
"Mohammod Lambert",
"Cassius Fritz",
"Lottie Coombes",
"Emily-Rose Odling",
"Regan Simmons",
"Tomas Roman",
"Adrienne Oconnell",
"Lukasz Wang",
"Kara Wilcox",
"Nelly Reeve",
"Bianka Palacios",
"Wilfred Mcdermott",
"Patrick Downs",
"Dionne Meyers",
"Jaxx Reid",
"Eduardo Gaines",
"Shauna Leech",
"Faisal Miles",
"Jared Mcclain",
"Ziggy Barrow",
"Norma North",
"Pascal Travis",
"Yasmin Riley",
"Lori Trevino",
"Lina Franks",
"Elleanor Gill",
"Emilis Lang",
"Lance Baxter",
"Rihanna Weber",
"Kylo Medina",
"Aneeka Strong",
"Roman Bateman",
"Forrest Evans",
"Zubair Mack",
"Gerard Burt",
"Abel Oconnor",
"Christian Fleming",
"Philippa Sheppard",
"Tanya Macleod",
"Sumayyah Mclaughlin",
"Aaran Carson",
"Aayan Mueller",
"Joss Dejesus",
"Kallum Watts",
"Chaya Lawson",
"Delilah Shea",
"Herman Major",
"Vivek Salt",
"Francis Chan",
"Anam Archer",
"Luca Irwin",
"Ana Cole",
"Myles Rossi",
"Derry Head",
"Anum Preston",
"Karim Deleon",
"Cecelia King",
"Stewart Gilmore",
"Bevan Bourne",
"Ehsan Jensen",
"Jayce Cullen",
"Safaa Sexton",
"Muneeb Flores",
"Hywel Chase",
"Eleasha Tran",
"River Ratcliffe",
"Sharna Rubio" };


int main()
{
	int randSize = 0;
	srand(time(NULL));

	Airplane airplane("Boeing 777X", 1);
	Crew crew = Crew("A Team");
	for (int i = 0; i < 2; i++) 
	{
		crew.addComponent(new Pilot(FIO(name_and_surname_arr[rand() % 300])));
	}

	for (int i = 0; i < 6; i++)
	{
		crew.addComponent(new FlightAttendant(FIO(name_and_surname_arr[rand() % 300])));
	}
	
	airplane.addComponent(&crew);

	randSize = rand() % 10 + 1;
	for (int i = 0; i < randSize; i++)
	{
		airplane.addComponent(new FirstClassPassenger(FIO(name_and_surname_arr[rand() % 300])));
	}

	randSize = rand() % 20 + 1;
	for (int i = 0; i < randSize; i++)
	{
		airplane.addComponent(new BusinessClassPassenger(FIO(name_and_surname_arr[rand() % 300])));
	}

	randSize = rand() % 150 + 1;
	for (int i = 0; i < randSize; i++)
	{
		airplane.addComponent(new EconomClassPassenger(FIO(name_and_surname_arr[rand() % 300])));
	}

	airplane.output();
	std::cout << std::endl;

	int totalWeightBaggage = airplane.getBaggageWeight();
	std::cout << "Total baggage weight: "<< totalWeightBaggage << std::endl;

	std::cout << "Write max baggage weight: ";
	int maxWeight;
	std::cin >> maxWeight;
	int* toRemove  = new int();
	*toRemove = totalWeightBaggage - maxWeight;
	airplane.removeOverload(toRemove);

	totalWeightBaggage = airplane.getBaggageWeight();
	std::cout << "Total baggage weight: " << totalWeightBaggage << std::endl;
	std::cout << "Airplane isReady: " << airplane.isReady() << std::endl;

	if ((!airplane.isReady()) || (totalWeightBaggage > maxWeight))
		std::cout << "Airplane can't fly!";
	else
		std::cout << "Airplane can fly)";

	return 0;
}
